#!/bin/bash

if [[ $# > 0 ]]; then
   while [[ $# > 0 ]]
   do
        echo
        echo "============================= Build \"$1\" ============================="
        echo
        docker build --no-cache -t $1 ./$1
        shift
   done
else
   echo "automatically build the dockers for various releases."
   echo "    build [release] ... [release]"
fi
